volumes:
  postgres-data-speedscape:
    external: true

services:
  db:
    container_name: postgresdb
    image: postgres:16.3
    ports:
      - 5432:5432
    restart: unless-stopped
    volumes:
      - postgres-data-speedscape:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres